import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import { TRPCReactProvider } from '@/trpc/client'
import type { ReactNode } from 'react'

const dmSans = DM_Sans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <TRPCReactProvider>
        <body className={`${dmSans.className} antialiased`}>{children}</body>
      </TRPCReactProvider>
    </html>
  )
}
