import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import { TRPCReactProvider } from '@/trpc/client'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import type { ReactNode } from 'react'

const dmSans = DM_Sans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <NuqsAdapter>
        <TRPCReactProvider>
          <body className={`${dmSans.className} antialiased`}>{children}</body>
          <Toaster />
        </TRPCReactProvider>
      </NuqsAdapter>
    </html>
  )
}
